export const Category = [
  "All",
  "General Search",
  "Main National Search Engines",
  "Meta Search",
  "Specialty Search Engines",
  "Visual Search and Clustering Search Engines",
  "Similar Sites Search",
  "Document and Slides Search",
  "File Search",
  "Pastebins",
  "Code Search",
  "Major Social Networks",
  "Realtime Search Social Media Search and General Social Media Tools",
  "Twitter",
  "Facebook",
  "Instagram",
  "Pinterest",
  "Reddit",
  "VKontakte",
  "Tumblr",
  "LinkedIn",
  "Telegram",
  "Blog Search",
  "Forums and Discussion Boards Search",
  "Username Check",
  "People Investigations Complete",
  "Email Search Check",
  "Phone Number Research",
  "Expert Search",
  "Company Research",
  "Job Search Resources",
  "QandA Sites",
  "Domain and IP Research",
  "Keywords Discovery and Research",
  "Web History and Website Capture",
  "Language Tools",
  "Image Search",
  "Image Analysis",
  "Video Search and Other Video Tools",
  "Geospatial Research and Mapping Tools",
  "News",
  "News Digest and Discovery Tools",
  "Fact Checking",
  "Data and Statistics",
  "Web Monitoring",
  "Browsers",
  "Offline Browsing",
  "VPN Services",
  "Infographics and Data Visualization",
  "Social Network Analysis",
  "Privacy and Encryption Tools",
  "DNS",
  "Maritime",
  "Other Tools",
  "Threat Intelligence",
  "OSINT Videos",
  "OSINT Blogs",
  "Other Resources",
  "Related Awesome Lists",
];
